- name: Create a EC2 instance to configure tomcat and apache
  hosts: localhost
  gather_facts: False
  roles:
     - ec2
- name: Configure instance(s) with tomcat and apache
  hosts: app
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: True
  tasks:
    - name: install apache and tomcat
      apt: name={{ item }} state=present update_cache=yes
      with_items:
            - apache2
            - tomcat7

