---
- name: Launch EC2 Ubuntu 14.04 instance
  ec2:
     key_name: "{{ key_name }}"
     group: "{{ security_group }}"
     instance_type: "{{ instance_type }}"
     image: "{{ image }}"
     wait: true
     region: "{{ region }}"
     vpc_subnet_id: subnet-053b0f4c
     assign_public_ip: yes
     count: 2
  register: ec2

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.private_ip }}"
    port: 22
    state: started
  with_items: '{{ec2.instances}}'

- name: Add instance to Ansible groups name called app
  add_host:
    groups: app
    name: "{{ item.private_ip }}"
  with_items: '{{ec2.instances}}'


